- hosts: nginx
  become: yes
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

- hosts: httpd
  become: yes
  tasks:
    - name: Install Httpd
      yum:
        name: httpd
        state: present
        update_cache: yes
