name: Solo Ansible Workflow

on:
  push:
    branches:
      - main

jobs:
  ansible-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add SSH Key
        run: |
          echo "${{ secrets.AWS_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Run Ansible Playbook for Nginx
        run: |
          ansible-playbook ansible_workflow/playbook.yml -i "${{ secrets.NGINX_IP }}," -u ${{ secrets.SSH_USER }} --private-key private_key.pem --extra-vars "host=nginx"
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"

      - name: Run Ansible Playbook for Httpd
        run: |
          ansible-playbook ansible_workflow/playbook.yml -i "${{ secrets.HTTPD_IP }}," -u ${{ secrets.SSH_USER }} --private-key private_key.pem --extra-vars "host=httpd"
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"

      - name: Clean up
        run: rm -f private_key.pem
